# Project Name
TARGET = Quantizer

# Sources
CPP_SOURCES = Quantizer.cpp

# Library Locations
LIBDAISY_DIR = $(DAISY_EXAMPLES_DIRECTORY)/libDaisy/
DAISYSP_DIR = $(DAISY_EXAMPLES_DIRECTORY)/DaisySP/

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
