# Project Name
TARGET = Quantizer

# Sources
CPP_SOURCES = Quantizer.cpp

# Library Locations
LIBDAISY_DIR = $(HOME)/Code/DaisyExamples/libDaisy/
DAISYSP_DIR = $(HOME)/Code/DaisyExamples/DaisySP/

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
